name: Convert Quarto to Jupyter Notebook
on:
  push:
    branches:
      - v0.0
    paths:
      - index.qmd
jobs:
  test-methods-hub-render:
    name: Convert Quarto to Jupyter Notebook
    uses: GESIS-Methods-Hub/qmd2ipynb@v2
    with:
      files: 'index.qmd'
      token: ${{ secrets.GITHUB_TOKEN }}
      
